CREATE TABLE Party (
	
	TableID INT AUTO_INCREMENT,
	ID INT NOT NULL,
	Pokemon VARCHAR (30),
	HPEV INT NOT NULL,
	ATEV INT NOT NULL,
	DEFEV INT NOT NULL,
	SATEV INT NOT NULL,
	SDEFEV INT NOT NULL,
	SPDEV INT NOT NULL,
	
	PRIMARY KEY TableID,
	FOREIGN KEY (ID) References Users (ID)
	);
	
